# Generated by Django 4.1.2 on 2023-11-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_datafile_options'),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observational_unit_id', models.CharField(max_length=100, unique=True)),
                ('collection_datetime', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
