version: "3.9"

services:
  web:
    build:
      context: ./django
    image: dif-django
    container_name: django_webapp
    command: python manage.py runserver 0.0.0.0:8080
    env_file:
      - .env.django
    volumes:
      - .:/home/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13-alpine
    env_file:
      - .env.django
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: