# Generated by Django 4.1.2 on 2022-10-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0002_remove_project_project_team_project_team_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.project')),
            ],
        ),
    ]
