# Generated by Django 4.1.2 on 2023-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0002_remove_project_project_team_project_team_member_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
