# Generated by Django 4.1.2 on 2023-06-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_rename_uploadedfile_datafile_alter_datafile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'verbose_name': 'Data File', 'verbose_name_plural': 'Data Files'},
        ),
    ]
